-- ===========================================================================
--  Run this ONCE in the Supabase SQL editor.
--  Dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--
--  The support button's audit trail.
--
--  The button's actual errand is email — a request is sent by the Apps Script
--  relay in apps-script/Code.gs and lands in the admins' inboxes, and that
--  happens whether or not this table exists. What this adds is the record: a
--  place the request survives a mailbox someone cleared, a deployment that was
--  down for an hour, or an argument about what was asked and when.
--
--  It also gives the rate limit something to count. Without this table the
--  action skips the check, which is the right trade when the alternative is a
--  support button that cannot send at all.
--
--  Nothing else in the schema depends on this file, so it can be run at any
--  point after the account tables exist.
-- ===========================================================================

begin;

create table if not exists public.support_requests (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,

  -- The name and address as they stood when the request was sent. Copied
  -- rather than joined on purpose: a reply months later should go to the
  -- address that asked the question, not to whatever the profile says now.
  name         text,
  email        text not null,

  subject      text not null,
  message      text not null,

  -- What the relay reported back. `false` here is the row worth reading:
  -- somebody asked for help and the mail did not leave.
  delivered    boolean not null default false,
  delivered_to text[] not null default '{}',

  created_at   timestamptz not null default now()
);

-- The rate limit counts one customer's rows inside a ten-minute window, which
-- is exactly this index. The second one is for reading the inbox newest-first.
create index if not exists support_requests_user_recent_idx
  on public.support_requests (user_id, created_at desc);

create index if not exists support_requests_recent_idx
  on public.support_requests (created_at desc);

alter table public.support_requests enable row level security;

-- Filing is the only write a customer gets. No update and no delete: an audit
-- trail somebody can edit after the fact is not one. `user_id = auth.uid()`
-- is what stops a request being filed in another account's name — the app
-- takes the identity from the session too, and these are the braces to that
-- belt.
drop policy if exists "Customers file their own requests" on public.support_requests;
create policy "Customers file their own requests" on public.support_requests
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Customers read their own requests" on public.support_requests;
create policy "Customers read their own requests" on public.support_requests
  for select to authenticated
  using (user_id = auth.uid());

-- is_admin() rather than a table read, so this answers the same way as every
-- other admin policy in the schema. Defined in supabase-admin-setup.sql.
drop policy if exists "Admins read every request" on public.support_requests;
create policy "Admins read every request" on public.support_requests
  for select to authenticated
  using (public.is_admin());

revoke all on public.support_requests from anon, authenticated;
grant select, insert on public.support_requests to authenticated;

commit;

-- ---------------------------------------------------------------------------
-- Check. Should list the three policies above, and the admin roster the
-- relay writes to — every address here receives support mail once
-- SUPABASE_SERVICE_ROLE_KEY is set in .env.local.
-- ---------------------------------------------------------------------------
select policyname, cmd from pg_policies where tablename = 'support_requests' order by policyname;
select name, email from public.admins order by id;
