-- ===========================================================================
--  Run this ONCE in the Supabase SQL editor.
--  Dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--
--  Wires your `admins` table (id int8, name, email) into the app:
--    register  ->  inserts a row here
--    log in    ->  looks for the user's email here. Found = admin. Not = customer.
--
--  Matching is on email, because your `id` is a counter rather than the user's
--  uuid. auth.users.email is unique, so it identifies a person just as well.
--
--  One transaction: if anything fails, nothing is applied.
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. Make the table safe to write to.
-- ---------------------------------------------------------------------------

-- If `id` has no default, inserts that do not name it would fail.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'admins' and column_name = 'id'
       and (is_identity = 'YES' or column_default is not null)
  ) then
    alter table public.admins alter column id add generated by default as identity;
  end if;
end
$$;

-- One row per person. Case-insensitive, because nobody types their own address
-- the same way twice and Supabase does not care about the difference.
create unique index if not exists admins_email_lower_key on public.admins (lower(email));

alter table public.admins enable row level security;

-- No direct writes from a browser, ever. The SECURITY DEFINER functions below
-- are the only things that add or remove a row — otherwise any signed-in
-- customer could insert their own email and become an admin.
revoke all on public.admins from anon, authenticated;
grant select on public.admins to authenticated;

drop policy if exists "Admins read the roster" on public.admins;
create policy "Admins read the roster" on public.admins
  for select to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- 2. Move whoever is already an admin into the table, BEFORE anything starts
--    reading it. Without this you would lock yourself out at step 5.
-- ---------------------------------------------------------------------------
insert into public.admins (name, email)
select p.full_name, u.email
from public.profiles p
join auth.users u on u.id = p.id
where p.is_admin
on conflict (lower(email)) do nothing;

-- ---------------------------------------------------------------------------
-- 3. The question the log-in asks: is this person in the admins table?
--
--    Every RLS policy on profiles and installer_verifications already calls
--    is_admin(), so repointing it here moves the whole app in one step.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from auth.users u
    join public.admins a on lower(a.email) = lower(u.email)
    where u.id = auth.uid()
  )
$$;

create or replace function public.admin_exists()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (select 1 from public.admins)
$$;

-- The panel needs to show a Make admin / Remove admin button per row, so it
-- has to know which uuids are admins. Guarded: only an admin may ask.
create or replace function public.admin_user_ids()
returns setof uuid
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    return;
  end if;

  return query
    select u.id
    from auth.users u
    join public.admins a on lower(a.email) = lower(u.email);
end;
$$;

revoke all on function public.is_admin() from public, anon;
revoke all on function public.admin_user_ids() from public, anon;
revoke all on function public.admin_exists() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_user_ids() to authenticated;
grant execute on function public.admin_exists() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. The writers.
-- ---------------------------------------------------------------------------

-- /admin/register — this is the "save it here" step.
create or replace function public.grant_admin_on_register()
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    return false;
  end if;

  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;

  return true;
end;
$$;

-- /admin/setup — an account that already exists, on a site with no admin yet.
create or replace function public.claim_first_admin()
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtext('claim_first_admin'));

  if exists (select 1 from public.admins) then
    return false;
  end if;

  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;

  return true;
end;
$$;

-- The buttons in the Accounts table. Takes the profile's uuid and resolves it
-- to an email, so the panel never has to know the table is keyed differently.
create or replace function public.set_admin(p_target uuid, p_value boolean)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid   uuid := auth.uid();
  v_email text;
begin
  if v_uid is null or not public.is_admin() then
    return false;
  end if;

  if p_target = v_uid and not p_value then
    raise exception 'You cannot remove your own admin access.' using errcode = 'check_violation';
  end if;

  select u.email into v_email from auth.users u where u.id = p_target;
  if v_email is null then
    return false;
  end if;

  if p_value then
    insert into public.admins (name, email)
    select p.full_name, v_email
    from public.profiles p
    where p.id = p_target
    on conflict (lower(email)) do nothing;
  else
    delete from public.admins where lower(email) = lower(v_email);
  end if;

  return true;
end;
$$;

revoke all on function public.grant_admin_on_register() from public, anon;
revoke all on function public.claim_first_admin() from public, anon;
revoke all on function public.set_admin(uuid, boolean) from public, anon;
grant execute on function public.grant_admin_on_register() to authenticated;
grant execute on function public.claim_first_admin() to authenticated;
grant execute on function public.set_admin(uuid, boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Cut the last two things still reading profiles.is_admin, then drop it.
--    Two places recording the same fact will disagree eventually; the admins
--    table is now the only answer.
-- ---------------------------------------------------------------------------

drop policy if exists "Admins can view all verification docs" on storage.objects;
create policy "Admins can view all verification docs" on storage.objects
  for select to authenticated
  using (bucket_id = 'verification-docs' and public.is_admin());

-- The guard trigger keeps its real job — stopping an applicant approving their
-- own verification — and loses the is_admin clauses along with the column.
create or replace function public.profiles_guard_privileged_columns()
returns trigger
language plpgsql
as $$
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin') or public.is_admin() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.verification_status :=
      case when new.customer_type = 'installer' then 'pending' else 'not_required' end;
  else
    if new.verification_status is distinct from old.verification_status
       and new.verification_status <> 'pending' then
      new.verification_status := old.verification_status;
    end if;
  end if;

  return new;
end;
$$;

alter table public.profiles drop column if exists is_admin;

-- ---------------------------------------------------------------------------
-- 6. Housekeeping: accounts left behind by testing. None of them is an admin.
-- ---------------------------------------------------------------------------
delete from public.profiles
 where id in (select id from auth.users
               where email like 'nocode-%@example.com'
                  or email like 'detached-%@example.com'
                  or email like 'repro-%@example.com'
                  or email like 'routing-%@example.com');

delete from auth.users
 where email like 'nocode-%@example.com'
    or email like 'detached-%@example.com'
    or email like 'repro-%@example.com'
    or email like 'routing-%@example.com';

commit;

-- ---------------------------------------------------------------------------
-- Check. `admins` should list whoever had access before you ran this, and the
-- column count should be 0.
-- ---------------------------------------------------------------------------
select id, name, email from public.admins order by id;

select count(*) as is_admin_column_should_be_zero
from information_schema.columns
where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_admin';
