-- ===========================================================================
--  VIP Solar — admin identity and account management.
--  Run this ONCE in the Supabase SQL editor.
--  Dashboard -> SQL Editor -> New query -> paste ALL of this -> Run.
--
--  This file owns ONE question: who is an admin, and what may they do to
--  accounts. It is the only definition of these seven functions, all of which
--  the app calls:
--
--    is_admin()                 every RLS policy, and the log-in's routing
--    admin_exists()             /admin/register and /admin/setup
--    admin_user_ids()           the Accounts table
--    grant_admin_on_register()  /admin/register
--    claim_first_admin()        /admin/setup
--    set_admin()                Make admin / Remove admin
--    delete_user_account()      the delete button
--
--  Products and orders live in the OTHER two files and are not touched here:
--    supabase-orders-checkout.sql        customer ordering + mark_order_paid()
--    supabase-admin-orders-products.sql  admin_set_order_status(), catalogue
--
--  Safe to run more than once.
-- ===========================================================================

begin;

-- ===========================================================================
-- 0. UNDO an earlier draft of this file.
--
--    A previous version of this script also tried to define products and
--    orders, before the checkout track existed. Its shapes do not match the
--    ones that shipped, and one of them is actively dangerous: a BEFORE INSERT
--    trigger on orders that writes a `reference` column the real table does
--    not have, which would fail every checkout. If that draft was ever run,
--    this removes it. If it was not, these are all no-ops.
-- ===========================================================================
drop trigger  if exists orders_set_reference on public.orders;
drop function if exists public.orders_set_reference();
drop sequence if exists public.order_reference_seq;
drop function if exists public.approve_order(uuid);
drop function if exists public.reject_order(uuid, text);
drop function if exists public.set_product_stock(text, integer);

drop policy if exists "Admins read orders"      on public.orders;
drop policy if exists "Admins read order items" on public.order_items;
drop policy if exists "Anyone reads products"   on public.products;
drop policy if exists "Admins write products"   on public.products;

-- The parallel catalogue columns that draft added. The live schema uses
-- retail_price / installer_price / stock_quantity / image_url instead, so
-- these were only ever going to be a second set of empty fields to confuse
-- whoever opened the table next. `installer_price` and `is_active` are NOT
-- dropped — those are the live schema's own.
drop index if exists public.products_model_key;
alter table public.products drop constraint if exists products_stock_non_negative;
alter table public.products drop column if exists model;
alter table public.products drop column if exists family;
alter table public.products drop column if exists photo;
alter table public.products drop column if exists srp;
alter table public.products drop column if exists stock;


-- ===========================================================================
-- 1. THE ADMINS TABLE
--    Keyed by email — `id` is a counter, not the user's uuid, and
--    auth.users.email is unique, so email identifies a person just as well.
-- ===========================================================================

create table if not exists public.admins (
  id    bigint generated by default as identity primary key,
  name  text,
  email text not null
);

-- If the table was made by hand in the Table Editor, `id` may have no default.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'admins' and column_name = 'id'
       and (is_identity = 'YES' or column_default is not null)
  ) then
    alter table public.admins alter column id add generated by default as identity;
  end if;
end
$$;

create unique index if not exists admins_email_lower_key on public.admins (lower(email));

alter table public.admins enable row level security;

-- No direct writes from a browser. Without this, any signed-in customer could
-- insert their own email with the public anon key and become an admin.
revoke all on public.admins from anon, authenticated;
grant select on public.admins to authenticated;

-- Whoever is already an admin moves across BEFORE anything reads the new
-- table. Guarded so the whole script can be run again later: once the column
-- has gone, this step has nothing to do rather than failing.
do $$
begin
  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_admin'
  ) then
    insert into public.admins (name, email)
    select p.full_name, u.email
    from public.profiles p
    join auth.users u on u.id = p.id
    where p.is_admin
    on conflict (lower(email)) do nothing;
  end if;
end
$$;


-- ===========================================================================
-- 2. THE READS
-- ===========================================================================

create or replace function public.is_admin()
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (
    select 1 from auth.users u
    join public.admins a on lower(a.email) = lower(u.email)
    where u.id = auth.uid()
  )
$$;

create or replace function public.admin_exists()
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (select 1 from public.admins)
$$;

-- The Accounts table needs to know which uuids are admins. Guarded.
create or replace function public.admin_user_ids()
returns setof uuid language plpgsql stable security definer
set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then return; end if;
  return query
    select u.id from auth.users u
    join public.admins a on lower(a.email) = lower(u.email);
end;
$$;

drop policy if exists "Admins read the roster" on public.admins;
create policy "Admins read the roster" on public.admins
  for select to authenticated using (public.is_admin());


-- ===========================================================================
-- 3. THE WRITES
-- ===========================================================================

-- /admin/register. Open by the site owner's explicit decision: anybody who
-- reaches that URL becomes an admin, and the path is the only secret.
create or replace function public.grant_admin_on_register()
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then return false; end if;
  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;
  return true;
end;
$$;

-- /admin/setup — an existing account, on a site with no admin yet.
create or replace function public.claim_first_admin()
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then return false; end if;
  perform pg_advisory_xact_lock(hashtext('claim_first_admin'));
  if exists (select 1 from public.admins) then return false; end if;
  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;
  return true;
end;
$$;

-- Make admin / Remove admin. Takes the profile's uuid and resolves it to an
-- email, so the panel never has to know the table is keyed differently.
create or replace function public.set_admin(p_target uuid, p_value boolean)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid(); v_email text;
begin
  if v_uid is null or not public.is_admin() then return false; end if;
  if p_target = v_uid and not p_value then
    raise exception 'You cannot remove your own admin access.' using errcode = 'check_violation';
  end if;

  select u.email into v_email from auth.users u where u.id = p_target;
  if v_email is null then return false; end if;

  if p_value then
    insert into public.admins (name, email)
    select p.full_name, v_email from public.profiles p where p.id = p_target
    on conflict (lower(email)) do nothing;
  else
    delete from public.admins where lower(email) = lower(v_email);
  end if;
  return true;
end;
$$;

-- ---------------------------------------------------------------------------
-- Deleting an account. Irreversible, so it refuses the one case a new sign-up
-- could not repair: deleting yourself.
--
-- Orders are deliberately NOT deleted. An order is a financial record and
-- should outlive the customer, so it is detached rather than destroyed.
-- ---------------------------------------------------------------------------
create or replace function public.delete_user_account(p_target uuid)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid(); v_email text;
begin
  if v_uid is null or not public.is_admin() then return false; end if;
  if p_target = v_uid then
    raise exception 'You cannot delete your own account.' using errcode = 'check_violation';
  end if;

  select u.email into v_email from auth.users u where u.id = p_target;
  if v_email is null then return false; end if;

  -- Blank the customer off their orders where the schema allows it, so the
  -- history survives without pointing at a person. If the column is NOT NULL
  -- the delete would fail on a foreign key several statements later, with a
  -- message about a constraint rather than about what to do — so it stops
  -- here instead and says so.
  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'orders'
       and column_name = 'user_id' and is_nullable = 'YES'
  ) then
    update public.orders set user_id = null where user_id = p_target;
  elsif exists (select 1 from public.orders where user_id = p_target) then
    raise exception
      'This account has orders against it and they cannot be detached. Cancel or reassign them first.'
      using errcode = 'check_violation';
  end if;

  delete from public.installer_verifications where profile_id = p_target;
  delete from public.admins   where lower(email) = lower(v_email);
  delete from public.profiles where id = p_target;
  delete from auth.users      where id = p_target;

  -- Verification documents they uploaded stay in the storage bucket under
  -- their uuid; SQL cannot reach object storage. Clear them from
  -- Storage -> verification-docs if it matters.
  return true;
end;
$$;


-- ===========================================================================
-- 4. RETIRE profiles.is_admin
--    Two places recording the same fact disagree eventually. public.admins is
--    now the only answer, so the column goes — along with the last two things
--    that read it.
-- ===========================================================================

drop policy if exists "Admins can view all verification docs" on storage.objects;
create policy "Admins can view all verification docs" on storage.objects
  for select to authenticated
  using (bucket_id = 'verification-docs' and public.is_admin());

-- The guard trigger keeps its real job — stopping an applicant approving their
-- own verification — and loses the is_admin clauses along with the column.
create or replace function public.profiles_guard_privileged_columns()
returns trigger language plpgsql as $$
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin') or public.is_admin() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.verification_status :=
      case when new.customer_type = 'installer' then 'pending' else 'not_required' end;
  else
    if new.verification_status is distinct from old.verification_status
       and new.verification_status <> 'pending' then
      new.verification_status := old.verification_status;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_guard_privileged_columns on public.profiles;
create trigger profiles_guard_privileged_columns
  before insert or update on public.profiles
  for each row execute function public.profiles_guard_privileged_columns();

alter table public.profiles drop column if exists is_admin;


-- ===========================================================================
-- 5. GRANTS
-- ===========================================================================
revoke all on function public.is_admin()                  from public, anon;
revoke all on function public.admin_user_ids()            from public, anon;
revoke all on function public.grant_admin_on_register()   from public, anon;
revoke all on function public.claim_first_admin()         from public, anon;
revoke all on function public.set_admin(uuid, boolean)    from public, anon;
revoke all on function public.delete_user_account(uuid)   from public, anon;
revoke all on function public.admin_exists()              from public;

grant execute on function public.is_admin()                to authenticated;
grant execute on function public.admin_user_ids()          to authenticated;
grant execute on function public.grant_admin_on_register() to authenticated;
grant execute on function public.claim_first_admin()       to authenticated;
grant execute on function public.set_admin(uuid, boolean)  to authenticated;
grant execute on function public.delete_user_account(uuid) to authenticated;
grant execute on function public.admin_exists()            to anon, authenticated;


-- ===========================================================================
-- 6. Test accounts left behind while building. None of them is an admin.
-- ===========================================================================
delete from public.installer_verifications
 where profile_id in (select id from auth.users where email like '%@example.com');
delete from public.profiles
 where id in (select id from auth.users where email like '%@example.com');
delete from auth.users where email like '%@example.com';

commit;

-- ===========================================================================
-- Check. `admins` should list whoever runs the site, and the column count 0.
-- ===========================================================================
select id, name, email from public.admins order by id;

select count(*) as is_admin_column_should_be_zero
from information_schema.columns
where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_admin';
