-- ===========================================================================
--  VIP Solar — back office schema. Run this ONCE in the Supabase SQL editor.
--  Dashboard -> SQL Editor -> New query -> paste ALL of this -> Run.
--
--  Sections:
--    1  admins table wiring        (register saves here, log in checks here)
--    2  products + stock           (the maintenance page)
--    3  orders + order_items       (the approve / reject page)
--    4  delete a user account      (the accounts page)
--    5  cleanup of test accounts
--
--  One transaction. If any statement fails, nothing is applied.
-- ===========================================================================

begin;

-- ===========================================================================
-- 1. ADMINS
--    Your table, keyed by email — `id` is a counter, not the user's uuid, and
--    auth.users.email is unique, so email identifies a person just as well.
-- ===========================================================================

do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'admins' and column_name = 'id'
       and (is_identity = 'YES' or column_default is not null)
  ) then
    alter table public.admins alter column id add generated by default as identity;
  end if;
end
$$;

create unique index if not exists admins_email_lower_key on public.admins (lower(email));

alter table public.admins enable row level security;

-- No direct writes from a browser. Without this, any signed-in customer could
-- insert their own email with the public anon key and become an admin.
revoke all on public.admins from anon, authenticated;
grant select on public.admins to authenticated;

-- Whoever is already an admin moves across BEFORE anything reads the new
-- table. Without this you lock yourself out when is_admin is dropped below.
insert into public.admins (name, email)
select p.full_name, u.email
from public.profiles p
join auth.users u on u.id = p.id
where p.is_admin
on conflict (lower(email)) do nothing;

create or replace function public.is_admin()
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (
    select 1 from auth.users u
    join public.admins a on lower(a.email) = lower(u.email)
    where u.id = auth.uid()
  )
$$;

create or replace function public.admin_exists()
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (select 1 from public.admins)
$$;

-- The accounts page needs to know which uuids are admins. Guarded.
create or replace function public.admin_user_ids()
returns setof uuid language plpgsql stable security definer
set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then return; end if;
  return query
    select u.id from auth.users u
    join public.admins a on lower(a.email) = lower(u.email);
end;
$$;

drop policy if exists "Admins read the roster" on public.admins;
create policy "Admins read the roster" on public.admins
  for select to authenticated using (public.is_admin());

-- /admin/register — the "save it here" step. Open by design.
create or replace function public.grant_admin_on_register()
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then return false; end if;
  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;
  return true;
end;
$$;

-- /admin/setup — an existing account, on a site with no admin yet.
create or replace function public.claim_first_admin()
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then return false; end if;
  perform pg_advisory_xact_lock(hashtext('claim_first_admin'));
  if exists (select 1 from public.admins) then return false; end if;
  insert into public.admins (name, email)
  select p.full_name, u.email
  from auth.users u left join public.profiles p on p.id = u.id
  where u.id = v_uid
  on conflict (lower(email)) do nothing;
  return true;
end;
$$;

-- The Make admin / Remove admin buttons.
create or replace function public.set_admin(p_target uuid, p_value boolean)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid(); v_email text;
begin
  if v_uid is null or not public.is_admin() then return false; end if;
  if p_target = v_uid and not p_value then
    raise exception 'You cannot remove your own admin access.' using errcode = 'check_violation';
  end if;

  select u.email into v_email from auth.users u where u.id = p_target;
  if v_email is null then return false; end if;

  if p_value then
    insert into public.admins (name, email)
    select p.full_name, v_email from public.profiles p where p.id = p_target
    on conflict (lower(email)) do nothing;
  else
    delete from public.admins where lower(email) = lower(v_email);
  end if;
  return true;
end;
$$;

-- The last two things reading profiles.is_admin, then the column goes.
drop policy if exists "Admins can view all verification docs" on storage.objects;
create policy "Admins can view all verification docs" on storage.objects
  for select to authenticated
  using (bucket_id = 'verification-docs' and public.is_admin());

create or replace function public.profiles_guard_privileged_columns()
returns trigger language plpgsql as $$
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin') or public.is_admin() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.verification_status :=
      case when new.customer_type = 'installer' then 'pending' else 'not_required' end;
  else
    if new.verification_status is distinct from old.verification_status
       and new.verification_status <> 'pending' then
      new.verification_status := old.verification_status;
    end if;
  end if;
  return new;
end;
$$;

alter table public.profiles drop column if exists is_admin;


-- ===========================================================================
-- 2. PRODUCTS + STOCK
--    Columns are added only if missing, so anything you already put on the
--    table survives. One row per SKU, not per family — stock is counted per
--    thing you can actually ship.
-- ===========================================================================

alter table public.products add column if not exists model           text;
alter table public.products add column if not exists name            text;
alter table public.products add column if not exists family          text;
alter table public.products add column if not exists photo           text;
alter table public.products add column if not exists srp             numeric(12,2);
alter table public.products add column if not exists installer_price numeric(12,2);
alter table public.products add column if not exists stock           integer not null default 0;
alter table public.products add column if not exists is_active       boolean not null default true;
alter table public.products add column if not exists updated_at      timestamptz not null default now();

-- Stock can be zero but never negative: a count of things on a shelf.
alter table public.products drop constraint if exists products_stock_non_negative;
alter table public.products add constraint products_stock_non_negative check (stock >= 0);

create unique index if not exists products_model_key on public.products (model);

-- The catalogue, from the models already on the site. Stock starts at zero —
-- the maintenance page is where the real numbers get typed in.
insert into public.products (model, name, family, photo) values
  ('HYX-H6K-LS',  'Low-voltage hybrid inverter 6.0 kW',   'H-LS Series', '/products/h6-8k-ls.png'),
  ('HYX-H8K-LS',  'Low-voltage hybrid inverter 8.0 kW',   'H-LS Series', '/products/h6-8k-ls.png'),
  ('HYX-H6K-HS',  'High-voltage hybrid inverter 6.0 kW',  'H-HS Series', '/products/h6-8k-hs.png'),
  ('HYX-H8K-HS',  'High-voltage hybrid inverter 8.0 kW',  'H-HS Series', '/products/h6-8k-hs.png'),
  ('HYX-E50-H3',  'High-voltage battery 5.12 kWh',        'E-H3 Series', '/products/e50-100-h3.png'),
  ('HYX-E100-H3', 'High-voltage battery 10.4 kWh',        'E-H3 Series', '/products/e50-100-h3.png'),
  ('HYX-E160-L',  'Low-voltage battery 16.07 kWh',        'E-L Series',  '/products/e160-l.png')
on conflict (model) do nothing;

alter table public.products enable row level security;

-- The catalogue is public reading; only an admin changes it.
drop policy if exists "Anyone reads products"  on public.products;
drop policy if exists "Admins write products"  on public.products;
create policy "Anyone reads products" on public.products
  for select to anon, authenticated using (true);
create policy "Admins write products" on public.products
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- The maintenance page writes through this rather than updating the row
-- directly, so "who may change stock" is answered in one place.
create or replace function public.set_product_stock(p_model text, p_stock integer)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then return false; end if;
  if p_stock is null or p_stock < 0 then
    raise exception 'Stock cannot be negative.' using errcode = 'check_violation';
  end if;

  update public.products
     set stock = p_stock, updated_at = now()
   where model = p_model;

  return found;
end;
$$;


-- ===========================================================================
-- 3. ORDERS
--    Admin-only for now: nothing on the public site creates one. Rows are
--    entered here or seeded, and the panel approves or rejects them.
-- ===========================================================================

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  reference       text unique,
  customer_id     uuid references auth.users (id) on delete set null,
  customer_name   text not null,
  customer_email  text,
  customer_phone  text,
  notes           text,
  status          text not null default 'pending'
                    check (status in ('pending', 'approved', 'rejected')),
  rejection_reason text,
  placed_at       timestamptz not null default now(),
  reviewed_at     timestamptz,
  reviewed_by     uuid references auth.users (id)
);

create table if not exists public.order_items (
  id          uuid primary key default gen_random_uuid(),
  order_id    uuid not null references public.orders (id) on delete cascade,
  -- The model is stored rather than a foreign key to products: an order is a
  -- record of what was agreed, and it must not change shape when the
  -- catalogue does.
  model       text not null,
  description text,
  quantity    integer not null check (quantity > 0),
  unit_price  numeric(12,2)
);

create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists orders_status_idx        on public.orders (status, placed_at);

-- A readable number for the phone: ORD-000001.
create sequence if not exists public.order_reference_seq;

create or replace function public.orders_set_reference()
returns trigger language plpgsql as $$
begin
  if new.reference is null then
    new.reference := 'ORD-' || lpad(nextval('public.order_reference_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists orders_set_reference on public.orders;
create trigger orders_set_reference
  before insert on public.orders
  for each row execute function public.orders_set_reference();

alter table public.orders      enable row level security;
alter table public.order_items enable row level security;

revoke all on public.orders      from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
grant select on public.orders      to authenticated;
grant select on public.order_items to authenticated;

drop policy if exists "Admins read orders"       on public.orders;
drop policy if exists "Admins read order items"  on public.order_items;
create policy "Admins read orders" on public.orders
  for select to authenticated using (public.is_admin());
create policy "Admins read order items" on public.order_items
  for select to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Approving takes the stock off the shelf, in the same transaction as the
-- status change. If any line is short, the whole approval fails and says so —
-- an approved order the warehouse cannot fill is worse than a refused one.
-- ---------------------------------------------------------------------------
create or replace function public.approve_order(p_order uuid)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare
  v_uid  uuid := auth.uid();
  v_item record;
  v_have integer;
begin
  if not public.is_admin() then return false; end if;

  if not exists (select 1 from public.orders where id = p_order and status = 'pending') then
    raise exception 'That order is not awaiting review.' using errcode = 'check_violation';
  end if;

  for v_item in
    select i.model, sum(i.quantity) as qty
    from public.order_items i
    where i.order_id = p_order
    group by i.model
  loop
    select p.stock into v_have from public.products p where p.model = v_item.model for update;

    if v_have is null then
      raise exception 'No product called % is in the catalogue.', v_item.model
        using errcode = 'check_violation';
    end if;

    if v_have < v_item.qty then
      raise exception 'Only % of % left in stock, and the order asks for %.',
        v_have, v_item.model, v_item.qty using errcode = 'check_violation';
    end if;

    update public.products
       set stock = stock - v_item.qty, updated_at = now()
     where model = v_item.model;
  end loop;

  update public.orders
     set status = 'approved', reviewed_at = now(), reviewed_by = v_uid, rejection_reason = null
   where id = p_order;

  return true;
end;
$$;

create or replace function public.reject_order(p_order uuid, p_reason text)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then return false; end if;

  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'A reason is required to reject an order.' using errcode = 'check_violation';
  end if;

  if not exists (select 1 from public.orders where id = p_order and status = 'pending') then
    raise exception 'That order is not awaiting review.' using errcode = 'check_violation';
  end if;

  -- Nothing to give back: stock only moves on approval.
  update public.orders
     set status = 'rejected', reviewed_at = now(), reviewed_by = auth.uid(),
         rejection_reason = btrim(p_reason)
   where id = p_order;

  return true;
end;
$$;


-- ===========================================================================
-- 4. DELETING AN ACCOUNT
--    Removes the auth user and everything hanging off it. Irreversible, so it
--    refuses on the one case that cannot be undone by making a new account:
--    deleting yourself.
-- ===========================================================================
create or replace function public.delete_user_account(p_target uuid)
returns boolean language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_uid uuid := auth.uid(); v_email text;
begin
  if v_uid is null or not public.is_admin() then return false; end if;
  if p_target = v_uid then
    raise exception 'You cannot delete your own account.' using errcode = 'check_violation';
  end if;

  select u.email into v_email from auth.users u where u.id = p_target;
  if v_email is null then return false; end if;

  delete from public.installer_verifications where profile_id = p_target;
  delete from public.admins  where lower(email) = lower(v_email);
  delete from public.profiles where id = p_target;
  delete from auth.users     where id = p_target;

  -- Any verification documents they uploaded stay in the storage bucket under
  -- their uuid; SQL cannot reach object storage. Clear them from
  -- Storage -> verification-docs if it matters.
  return true;
end;
$$;


-- ===========================================================================
-- 5. GRANTS + CLEANUP
-- ===========================================================================
revoke all on function public.is_admin()                             from public, anon;
revoke all on function public.admin_user_ids()                       from public, anon;
revoke all on function public.grant_admin_on_register()              from public, anon;
revoke all on function public.claim_first_admin()                    from public, anon;
revoke all on function public.set_admin(uuid, boolean)               from public, anon;
revoke all on function public.set_product_stock(text, integer)       from public, anon;
revoke all on function public.approve_order(uuid)                    from public, anon;
revoke all on function public.reject_order(uuid, text)               from public, anon;
revoke all on function public.delete_user_account(uuid)              from public, anon;
revoke all on function public.admin_exists()                         from public;

grant execute on function public.is_admin()                       to authenticated;
grant execute on function public.admin_user_ids()                 to authenticated;
grant execute on function public.grant_admin_on_register()        to authenticated;
grant execute on function public.claim_first_admin()              to authenticated;
grant execute on function public.set_admin(uuid, boolean)         to authenticated;
grant execute on function public.set_product_stock(text, integer) to authenticated;
grant execute on function public.approve_order(uuid)              to authenticated;
grant execute on function public.reject_order(uuid, text)         to authenticated;
grant execute on function public.delete_user_account(uuid)        to authenticated;
grant execute on function public.admin_exists()                   to anon, authenticated;

delete from public.installer_verifications
 where profile_id in (select id from auth.users where email like '%@example.com');
delete from public.profiles
 where id in (select id from auth.users where email like '%@example.com');
delete from auth.users where email like '%@example.com';

commit;

-- ===========================================================================
-- Check.
-- ===========================================================================
select id, name, email from public.admins order by id;
select model, name, stock from public.products order by model;
select count(*) as is_admin_column_should_be_zero
from information_schema.columns
where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_admin';
